version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo17_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo17_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./property:/mnt/extra-addons
      - ./property/theme:/mnt/extra-addons/theme
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped

volumes:
  odoo17_db_data:
